'use server';

import { headers } from 'next/headers';
import { bookingSchema } from '@/lib/validation';
import { calculatePrice } from '@/lib/pricing';
import { createAdminClient } from '@/lib/supabase/admin';
import { getSessionUser } from '@/lib/auth';
import { isSupabaseConfigured } from '@/lib/env';
import { checkRateLimit, clientKey, RATE_LIMITS } from '@/lib/rate-limit';
import { sendBookingConfirmation } from '@/lib/notifications';
import { getT } from '@/lib/i18n/server';

export type BookingResult =
  /**
   * `confirmationSent` sagt, ob die Bestätigungsmail tatsächlich rausging.
   * Die Erfolgsseite behauptete das bisher immer — auch wenn kein
   * Versanddienst konfiguriert war oder der Anbieter die Mail abgelehnt hat.
   */
  | { ok: true; trackingNumber: string; confirmationSent: boolean }
  | { ok: false; error: string; fieldErrors?: Record<string, string> };

/**
 * Creates a shipment.
 *
 * Security notes:
 *  - The price is recalculated here from the validated weight and pickup flag.
 *    Whatever total the browser displayed is ignored entirely.
 *  - The tracking number and the scan token are generated by the database
 *    trigger, never by this code and never by the client.
 *  - The status always starts at BOOKED.
 *  - Guests may book without an account; if someone is signed in we link the
 *    shipment to them so it shows up in /konto.
 */
export async function createBooking(input: unknown): Promise<BookingResult> {
  const t = await getT();
  if (!isSupabaseConfigured()) {
    return {
      ok: false,
      error:
        'Die Datenbank ist noch nicht konfiguriert. Bitte hinterlege die Supabase-Zugangsdaten (.env.local).',
    };
  }

  const parsed = bookingSchema.safeParse(input);
  if (!parsed.success) {
    const fieldErrors: Record<string, string> = {};
    for (const issue of parsed.error.issues) {
      const key = issue.path.join('.');
      if (key && !fieldErrors[key]) fieldErrors[key] = issue.message;
    }
    return { ok: false, error: t('actions.checkInput'), fieldErrors };
  }

  const data = parsed.data;

  const requestHeaders = await headers();
  const limit = checkRateLimit(
    clientKey(requestHeaders, 'booking'),
    RATE_LIMITS.booking.limit,
    RATE_LIMITS.booking.windowMs,
  );
  if (!limit.allowed) {
    return {
      ok: false,
      error: `Zu viele Buchungen in kurzer Zeit. Bitte versuche es in ${limit.retryAfterSeconds} Sekunden erneut.`,
    };
  }

  // --- Price: server-side, from the central pricing function -----------------
  const price = calculatePrice({
    weightKg: data.weightKg,
    pickupRequested: data.pickupRequested,
    shipmentType: data.shipmentType,
  });

  const supabase = createAdminClient();
  const user = await getSessionUser();

  // --- Customer record -------------------------------------------------------
  let customerId: string | null = null;
  try {
    const { data: existing } = await supabase
      .from('customers')
      .select('id, profile_id')
      // Both schemas lower-case the address, so an exact match is correct here
      // — and unlike ILIKE it cannot be widened by "_" or "%" inside an e-mail.
      .eq('phone', data.senderPhone)
      .eq('email', data.senderEmail)
      .maybeSingle();

    if (existing) {
      customerId = existing.id;

      // `profile_id` is deliberately never written here. Linking an address-book
      // entry to a login grants that login access to the entry's whole shipment
      // history via row level security — so knowing somebody's phone number and
      // e-mail address must not be enough to claim it. New bookings by a
      // signed-in user are still found through `created_by`.
      //
      // For the same reason we only refresh the contact details when the record
      // is unclaimed or already belongs to the person booking.
      if (!existing.profile_id || existing.profile_id === user?.id) {
        await supabase
          .from('customers')
          .update({
            first_name: data.senderFirstName,
            last_name: data.senderLastName,
            address_line1: data.senderAddress,
            postal_code: data.senderPostalCode,
            city: data.senderCity,
            country: data.senderCountry,
          })
          .eq('id', existing.id);
      }
    } else {
      const { data: created } = await supabase
        .from('customers')
        .insert({
          profile_id: user?.id ?? null,
          first_name: data.senderFirstName,
          last_name: data.senderLastName,
          email: data.senderEmail,
          phone: data.senderPhone,
          address_line1: data.senderAddress,
          postal_code: data.senderPostalCode,
          city: data.senderCity,
          country: data.senderCountry,
        })
        .select('id')
        .single();
      customerId = created?.id ?? null;
    }
  } catch (error) {
    // A missing customer record must not block the booking itself.
    console.error('[booking] Kundendatensatz konnte nicht angelegt werden:', error);
  }

  // --- Shipment --------------------------------------------------------------
  const now = new Date().toISOString();

  const { data: shipment, error } = await supabase
    .from('shipments')
    .insert({
      // tracking_number and scan_token are assigned by the database trigger —
      // deliberately absent here so no code path can influence them.
      shipment_type: data.shipmentType,
      status: 'BOOKED',
      customer_id: customerId,
      created_by: user?.id ?? null,

      sender_first_name: data.senderFirstName,
      sender_last_name: data.senderLastName,
      sender_phone: data.senderPhone,
      sender_email: data.senderEmail,
      sender_address: data.senderAddress,
      sender_postal_code: data.senderPostalCode,
      sender_city: data.senderCity,
      sender_country: data.senderCountry,

      recipient_first_name: data.recipientFirstName,
      recipient_last_name: data.recipientLastName,
      recipient_phone: data.recipientPhone,
      recipient_address: data.recipientAddress,
      recipient_city: data.recipientCity,
      recipient_country: data.recipientCountry,

      origin_country: data.originCountry,
      origin_city: data.originCity,
      destination_country: data.destinationCountry,
      destination_city: data.destinationCity,

      weight_kg: data.weightKg,
      piece_count: data.pieceCount,
      content_type: data.contentType,
      description: data.description,

      pickup_requested: data.pickupRequested,
      pickup_date: data.pickupDate,

      price_base_cents: price.basePriceCents,
      pickup_fee_cents: price.pickupFeeCents,
      price_total_cents: price.totalCents,
      payment_status: 'unpaid',

      terms_accepted_at: now,
      prohibited_confirmed_at: now,
    })
    .select('id, tracking_number')
    .single();

  if (error || !shipment) {
    console.error('[booking] Sendung konnte nicht angelegt werden:', error?.message);
    return {
      ok: false,
      error: t('actions.bookingFailed'),
    };
  }

  // --- Pickup assignment -----------------------------------------------------
  if (data.pickupRequested && data.pickupDate) {
    const { error: pickupError } = await supabase.from('pickup_assignments').insert({
      shipment_id: shipment.id,
      scheduled_date: data.pickupDate,
      status: 'scheduled',
      note: 'Wunschtermin des Kunden aus der Onlinebuchung',
    });
    if (pickupError) {
      console.error('[booking] Abholung konnte nicht eingeplant werden:', pickupError.message);
    }
  }

  // --- Confirmation ----------------------------------------------------------
  // Never let a mail problem fail a booking that is already stored — but do
  // report whether it worked, so the page does not claim a mail nobody sent.
  let confirmationSent = false;
  try {
    const delivery = await sendBookingConfirmation(
      { email: data.senderEmail, whatsapp: data.senderPhone },
      {
        trackingNumber: shipment.tracking_number,
        customerFirstName: data.senderFirstName,
        originCity: data.originCity,
        destinationCity: data.destinationCity,
        weightKg: data.weightKg,
        pieceCount: data.pieceCount,
        priceTotalCents: price.totalCents,
      },
      shipment.id,
    );
    confirmationSent = delivery.emailDelivered;
  } catch (notifyError) {
    console.error('[booking] Bestätigung konnte nicht versendet werden:', notifyError);
  }

  return { ok: true, trackingNumber: shipment.tracking_number, confirmationSent };
}
